### ISSUE TITLE
Multiple relations between entities naming policy

### ISSUE THREAD

**Issue by RadeKornjaca** [danielkupco/PyMaJORME#8]
For example, if there are relations between two entities that are manifested as collection in Java class, what would be the policy for naming those collections?

**Comment by RadeKornjaca** [comment]
Example: 

```
ElementType -> Element
ElementType <-> Element
```

Proposition (in ElementType.java class):

```
private List<Element> elements;
private List<Element> elements2;
```

**Comment by danielkupco** [comment]
If no field name is specified on either side, the proposition mentioned above looks fine.
Otherwise, specified field name should be taken into account (syntax is not specified for this part yet, so feel free to choose what you consider as most appropriate), e.g. :

`ElementType [firstElements] -> Element [firstElementType]`
`ElementType [secondElements] <-> Element [secondElementTypes]`
